library(data.table)
ex.proj1 <- fread("household_power_consumption.txt", sep=";", header=TRUE)
ex.proj1$Date <- as.Date(ex.proj1$Date, "%d/%m/%Y")
ex.proj1 <- ex.proj1[ex.proj1$Date>="2007-02-01" & ex.proj1$Date<="2007-02-02",]
ex.proj1 <- as.data.frame(ex.proj1)
ex.proj1$Time.1 <- strptime(paste(ex.proj1$Date, ex.proj1$Time), "%Y-%m-%d %H:%M:%S")
ex.proj1$Global_active_power.1 <- as.numeric(ex.proj1$Global_active_power)
ex.proj1$Global_reactive_power.1 <- as.numeric(ex.proj1$Global_reactive_power)
ex.proj1$Voltage.1 <- as.numeric(ex.proj1$Voltage)
ex.proj1$Global_intensity.1 <- as.numeric(ex.proj1$Global_intensity)
ex.proj1$Sub_metering_1.1 <- as.numeric(ex.proj1$Sub_metering_1)
ex.proj1$Sub_metering_2.1 <- as.numeric(ex.proj1$Sub_metering_2)

hist(ex.proj1$Global_active_power.1, col="red", xlab="Global Active Power (kilowatts)", main="Global Active Power")
dev.copy(png, file="plot1.png", width=480, height=480, units="px")
dev.off()
